# Generated by Django 5.2.15 on 2026-06-17 15:20

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_code", models.CharField(db_index=True, max_length=64)),
                ("stat_date", models.DateField(db_index=True)),
                (
                    "dimension_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="维度取值，空为总量",
                        max_length=64,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "指标快照",
                "verbose_name_plural": "指标快照",
                "db_table": "ana_metric_snapshot",
                "ordering": ["-stat_date"],
                "unique_together": {("metric_code", "stat_date", "dimension_key")},
            },
        ),
    ]
