# Generated by Django 5.2.15 on 2026-06-04 15:25

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(max_length=40, unique=True)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='open', max_length=32)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='masterdata.customer')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'ops_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waybill_no', models.CharField(max_length=40, unique=True)),
                ('route_name', models.CharField(max_length=160)),
                ('origin', models.CharField(blank=True, max_length=80)),
                ('destination', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_dispatch', '待调度'), ('dispatched', '已派车'), ('loaded', '已装车'), ('departed', '已发车'), ('in_transit', '运输中'), ('arrived', '已到达'), ('signed', '已签收'), ('delivered', '已送达'), ('settled', '已结算'), ('cancelled', '已取消'), ('voided', '已作废')], default='pending_dispatch', max_length=32)),
                ('dispatch_status', models.CharField(default='pending_accept', max_length=32)),
                ('risk_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低'), ('none', '无')], default='none', max_length=16)),
                ('receipt_status', models.CharField(default='not_due', max_length=32)),
                ('eta_drift_minutes', models.IntegerField(default=0)),
                ('cargo_quantity', models.IntegerField(default=0)),
                ('cargo_weight_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cargo_volume_cbm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='masterdata.carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='masterdata.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='masterdata.driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='ops.order')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='iam.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='masterdata.vehicle')),
            ],
            options={
                'verbose_name': '运单',
                'verbose_name_plural': '运单',
                'db_table': 'ops_waybill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reported_at', models.DateTimeField()),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='ops.waybill')),
            ],
            options={
                'verbose_name': '轨迹点',
                'verbose_name_plural': '轨迹点',
                'db_table': 'ops_tracking_point',
                'ordering': ['reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='pending_handle', max_length=32)),
                ('responsibility_party', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='ops.waybill')),
            ],
            options={
                'verbose_name': '异常',
                'verbose_name_plural': '异常',
                'db_table': 'ops_exception',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('event_time', models.DateTimeField()),
                ('resource', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ops.waybill')),
            ],
            options={
                'verbose_name': '运单事件',
                'verbose_name_plural': '运单事件',
                'db_table': 'ops_waybill_event',
                'ordering': ['event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['status', 'risk_level'], name='ops_waybill_status_3d42b9_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['receipt_status'], name='ops_waybill_receipt_6f94a1_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['-eta_drift_minutes'], name='ops_waybill_eta_dri_ba2c68_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['customer', 'status'], name='ops_waybill_custome_9a905a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingpoint',
            index=models.Index(fields=['waybill', 'reported_at'], name='ops_trackin_waybill_bc72ea_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['exception_type', 'status'], name='ops_excepti_excepti_537100_idx'),
        ),
        migrations.AddIndex(
            model_name='waybillevent',
            index=models.Index(fields=['waybill', 'event_time'], name='ops_waybill_waybill_8e4f34_idx'),
        ),
        migrations.AddIndex(
            model_name='waybillevent',
            index=models.Index(fields=['event_type', 'event_time'], name='ops_waybill_event_t_7333da_idx'),
        ),
    ]
