# Generated by Django 5.2.15 on 2026-06-04 16:16

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_type', models.CharField(default='signed_pod', max_length=32)),
                ('status', models.CharField(default='uploaded', help_text='uploaded/confirmed/rejected', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('file_url', models.URLField(blank=True, help_text='外部已上传文件 URL')),
                ('ocr_status', models.CharField(default='pending', help_text='pending/processing/done/failed', max_length=16)),
                ('ocr_result', models.JSONField(blank=True, default=dict)),
                ('signatory', models.CharField(blank=True, max_length=80)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '回单',
                'verbose_name_plural': '回单',
                'db_table': 'ops_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='level',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='source',
            field=models.CharField(default='manual', help_text='manual/track/ocr/customer', max_length=32),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['level', 'status'], name='ops_excepti_level_d824cc_idx'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='ops.waybill'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['waybill', 'status'], name='ops_receipt_waybill_50f53e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['ocr_status'], name='ops_receipt_ocr_sta_9f0df2_idx'),
        ),
    ]
