# Generated by Django 5.2.15 on 2026-06-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0002_route_driver_license_expiry_driver_license_type_and_more"),
        ("ops", "0002_receipt_exceptionrecord_assignee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="planned_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waybills",
                to="masterdata.route",
            ),
        ),
    ]
