# Generated by Django 5.2.15 on 2026-06-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0003_waybill_planned_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="拆单/合单血缘：拆出的子单指向原单；合并的源单指向合并单",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="ops.waybill",
            ),
        ),
    ]
