# Generated by Django 5.2.15 on 2026-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0003_vehicle_load_capacity_ton_and_more"),
        ("ops", "0004_waybill_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cargo_desc",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="cargo_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="cargo_volume_cbm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="cargo_weight_ton",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="channel",
            field=models.CharField(
                choices=[
                    ("cs", "客服代下"),
                    ("self", "客户自助"),
                    ("miniprogram", "小程序"),
                    ("wechat_group", "微信群"),
                    ("api", "开放API"),
                ],
                db_index=True,
                default="cs",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="destination",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_pickup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="origin",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="parse_meta",
            field=models.JSONField(
                blank=True, default=dict, help_text="AI 解析来源与置信信息"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="raw_text",
            field=models.TextField(
                blank=True, help_text="原始消息（微信群/自然语言建单）"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="source",
            field=models.CharField(
                blank=True, help_text="渠道内来源标识，如群名/坐席", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="pending_confirm", max_length=32),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["channel", "status"], name="ops_order_channel_fa436f_idx"
            ),
        ),
    ]
