# Generated by Django 5.2.15 on 2026-06-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0003_vehicle_load_capacity_ton_and_more"),
        ("ops", "0005_order_cargo_desc_order_cargo_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=64, unique=True)),
                ("value", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "ops_number_counter",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("ftl", "整车"),
                    ("ltl", "零担"),
                    ("express", "快递"),
                    ("coldchain", "冷链"),
                ],
                default="ftl",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cargo_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="货值（保险/风控）",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_contact_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_hazardous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="package_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_contact_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pooled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="priority",
            field=models.CharField(
                choices=[("normal", "普通"), ("urgent", "加急"), ("vip", "VIP")],
                default="normal",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quoted_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="order",
            name="settlement_type",
            field=models.CharField(
                choices=[("monthly", "月结"), ("cash", "现结"), ("prepaid", "预付")],
                default="monthly",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("individual", "个人"),
                    ("enterprise", "企业"),
                    ("government", "政府"),
                ],
                default="enterprise",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="temperature_range",
            field=models.CharField(
                blank=True, help_text="冷链温区，如 -18~0", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                db_index=True, default="pending_confirm", max_length=32
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "priority"], name="ops_order_status_1209e9_idx"
            ),
        ),
    ]
