# Generated by Django 5.2.15 on 2026-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0006_numbercounter_order_business_type_order_cargo_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="dispatch_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("own_vehicle", "自有单车"),
                    ("fleet", "自有车队"),
                    ("third_party", "三方承运商"),
                ],
                max_length=16,
            ),
        ),
    ]
