# Generated by Django 5.2.15 on 2026-06-17 15:50

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0007_waybill_dispatch_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=48)),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="cs/dispatch/system/ai", max_length=24
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "event_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ops.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单事件",
                "verbose_name_plural": "订单事件",
                "db_table": "ops_order_event",
                "ordering": ["event_time"],
                "indexes": [
                    models.Index(
                        fields=["order", "event_time"],
                        name="ops_order_e_order_i_a03619_idx",
                    )
                ],
            },
        ),
    ]
