# Generated by Django 5.2.15 on 2026-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0008_orderevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="sign_source",
            field=models.CharField(
                blank=True, help_text="driver/customer", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="signature",
            field=models.TextField(blank=True, help_text="电子签名（dataURL/base64）"),
        ),
    ]
