# Generated by Django 5.2.15 on 2026-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0009_receipt_sign_source_receipt_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sla_status",
            field=models.CharField(
                choices=[
                    ("pending", "进行中"),
                    ("at_risk", "临期"),
                    ("on_time", "准时"),
                    ("breached", "超时"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
