# Generated by Django 5.2.15 on 2026-06-18 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0003_vehicle_load_capacity_ton_and_more"),
        ("ops", "0010_order_delivered_at_order_sla_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_by", "status"], name="ops_order_created_976dff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["claimed_by", "status"], name="ops_order_claimed_1eb254_idx"
            ),
        ),
    ]
