# Generated by Django 5.2.15 on 2026-06-18 02:25

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0011_order_ops_order_created_976dff_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCargoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "weight_ton",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "volume_cbm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("package_type", models.CharField(blank=True, max_length=32)),
                ("temperature_range", models.CharField(blank=True, max_length=32)),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_items",
                        to="ops.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "货物明细",
                "verbose_name_plural": "货物明细",
                "db_table": "ops_order_cargo_item",
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="OrderStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveIntegerField(default=1)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[("pickup", "提货"), ("delivery", "送货")],
                        default="pickup",
                        max_length=12,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=64)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("expected_start", models.DateTimeField(blank=True, null=True)),
                ("expected_end", models.DateTimeField(blank=True, null=True)),
                ("cargo_note", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="ops.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "装卸站点",
                "verbose_name_plural": "装卸站点",
                "db_table": "ops_order_stop",
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="OrderTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="订单字段 + 货物明细 + 站点 的快照"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "录单模板",
                "verbose_name_plural": "录单模板",
                "db_table": "ops_order_template",
                "ordering": ["-created_at"],
            },
        ),
    ]
