# Generated by Django 5.2.15 on 2026-06-18 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0012_ordercargoitem_orderstop_ordertemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="approval_remark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("none", "无需审批"),
                    ("pending", "待审批"),
                    ("approved", "已通过"),
                    ("rejected", "已驳回"),
                ],
                db_index=True,
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
