# Generated by Django 5.2.15 on 2026-06-18 03:03

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0013_order_approval_remark_order_approval_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "合同"),
                            ("authorization", "委托书"),
                            ("photo", "货物照片"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="order_attachments/"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, help_text="外部已上传文件 URL"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ops.order",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "订单附件",
                "verbose_name_plural": "订单附件",
                "db_table": "ops_order_attachment",
                "ordering": ["-created_at"],
            },
        ),
    ]
