# Generated by Django 5.2.15 on 2026-06-18 07:52

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0004_driver_employment_type_vehicle_vehicle_class"),
        ("ops", "0014_orderattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="trailer",
            field=models.ForeignKey(
                blank=True,
                help_text="挂车（牵引车 vehicle + 挂车 trailer）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trailer_waybills",
                to="masterdata.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="WaybillDriver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("main", "主驾"), ("co", "副驾"), ("relay", "接力")],
                        db_index=True,
                        default="main",
                        max_length=12,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="负责区间/备注，如 武汉→成都",
                        max_length=120,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waybill_assignments",
                        to="masterdata.driver",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_assignments",
                        to="ops.waybill",
                    ),
                ),
            ],
            options={
                "verbose_name": "运单司机",
                "verbose_name_plural": "运单司机",
                "db_table": "ops_waybill_driver",
                "ordering": ["role", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("waybill", "driver"), name="uniq_waybill_driver"
                    )
                ],
            },
        ),
    ]
