# Generated by Django 5.2.15 on 2026-06-18 08:13

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0015_waybill_trailer_waybilldriver"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waybill",
            name="departed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waybill",
            name="loaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waybill",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WaybillStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveIntegerField(default=1)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[("pickup", "提货"), ("delivery", "送货")],
                        default="pickup",
                        max_length=12,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=64)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "radius_m",
                    models.PositiveIntegerField(
                        default=800, help_text="到达围栏半径(米)"
                    ),
                ),
                ("planned_eta", models.DateTimeField(blank=True, null=True)),
                ("actual_arrival_at", models.DateTimeField(blank=True, null=True)),
                ("actual_depart_at", models.DateTimeField(blank=True, null=True)),
                (
                    "arrival_source",
                    models.CharField(
                        blank=True, help_text="gps/manual/sms", max_length=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待到达"),
                            ("arrived", "已到达"),
                            ("departed", "已离开"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="ops.waybill",
                    ),
                ),
            ],
            options={
                "verbose_name": "运单点位",
                "verbose_name_plural": "运单点位",
                "db_table": "ops_waybill_stop",
                "ordering": ["waybill", "seq"],
                "indexes": [
                    models.Index(
                        fields=["waybill", "seq"], name="ops_waybill_waybill_ca40c6_idx"
                    )
                ],
            },
        ),
    ]
