# Generated by Django 5.2.15 on 2026-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0016_waybill_arrived_at_waybill_departed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ai_conversation_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="AI会话ID（关联智能客服对话）",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="ai_conversation_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="AI会话ID（沿订单带入）",
                max_length=64,
            ),
        ),
    ]
