# Generated by Django 5.2.15 on 2026-06-23 08:45

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0005_customer_wechat_group_driver_app_registered_and_more"),
        ("ops", "0017_order_ai_conversation_id_waybill_ai_conversation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_no", models.CharField(max_length=40, unique=True)),
                ("template_code", models.CharField(default="standard", max_length=32)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="合同内容（文本，PDF 由此生成）"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, help_text="AI发送时间", null=True),
                ),
                (
                    "driver_reply",
                    models.CharField(blank=True, help_text="司机回复", max_length=255),
                ),
                (
                    "confirm_status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("confirmed", "已确认"),
                            ("rejected", "已拒签"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        help_text="自动生成的合同PDF",
                        null=True,
                        upload_to="contracts/",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="masterdata.driver",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="ops.waybill",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同",
                "verbose_name_plural": "合同",
                "db_table": "ops_contract",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["waybill", "confirm_status"],
                        name="ops_contrac_waybill_4bfe2d_idx",
                    )
                ],
            },
        ),
    ]
