# Generated by Django 5.2.15 on 2026-06-23 09:58

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0006_drivercredential"),
        ("ops", "0018_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="分类，如 装货/打卡/回单/安全",
                        max_length=32,
                    ),
                ),
                ("content", models.TextField(help_text="富文本内容（HTML/纯文本）")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "提醒模板",
                "verbose_name_plural": "提醒模板",
                "db_table": "ops_reminder_template",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DriverReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="作业提醒", max_length=120)),
                ("content", models.TextField()),
                (
                    "ack_required",
                    models.BooleanField(default=True, help_text="是否强制确认"),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=16),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="masterdata.driver",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="ops.waybill",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="ops.remindertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "司机提醒",
                "verbose_name_plural": "司机提醒",
                "db_table": "ops_driver_reminder",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["driver", "status"],
                        name="ops_driver__driver__de34a4_idx",
                    ),
                    models.Index(
                        fields=["waybill", "status"],
                        name="ops_driver__waybill_408273_idx",
                    ),
                ],
            },
        ),
    ]
