# Generated by Django 5.2.15 on 2026-06-23 10:07

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0006_drivercredential"),
        ("ops", "0019_remindertemplate_driverreminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverCheckin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.CharField(
                        choices=[
                            ("depart", "出发"),
                            ("arrive_pickup", "到达装货地"),
                            ("queuing", "排队"),
                            ("loading", "装货"),
                            ("depart_loaded", "发车"),
                            ("in_transit", "在途打卡"),
                            ("arrive_delivery", "到达卸货地"),
                            ("unloading", "卸货"),
                            ("receipt", "回单"),
                            ("finish", "订单结束"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        help_text="水印照片",
                        null=True,
                        upload_to="checkins/",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("checkin_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins",
                        to="masterdata.driver",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="ops.waybill",
                    ),
                ),
            ],
            options={
                "verbose_name": "司机打卡",
                "verbose_name_plural": "司机打卡",
                "db_table": "ops_driver_checkin",
                "ordering": ["-checkin_at"],
                "indexes": [
                    models.Index(
                        fields=["waybill", "node"],
                        name="ops_driver__waybill_73834f_idx",
                    )
                ],
            },
        ),
    ]
