# Generated by Django 5.2.15 on 2026-06-30 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_apikey"),
        ("masterdata", "0007_b2bpartner"),
        ("ops", "0020_drivercheckin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="ops_order_status_21f696_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waybill",
            index=models.Index(
                fields=["status", "-created_at"], name="ops_waybill_status_4d8c84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waybill",
            index=models.Index(
                fields=["driver", "status"], name="ops_waybill_driver__37467a_idx"
            ),
        ),
    ]
