# Generated by Django 5.2.15 on 2026-06-30 23:23

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0021_order_ops_order_status_21f696_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=48)),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "event_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exception_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ops.exceptionrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "异常处置事件",
                "verbose_name_plural": "异常处置事件",
                "db_table": "ops_exception_event",
                "ordering": ["event_time"],
                "indexes": [
                    models.Index(
                        fields=["exception", "event_time"],
                        name="ops_excepti_excepti_97f11f_idx",
                    )
                ],
            },
        ),
    ]
