# Generated by Django 5.2.15 on 2026-06-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0022_exceptionevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exceptionrecord",
            name="exception_type",
            field=models.CharField(
                choices=[
                    ("transit_delay", "在途超时"),
                    ("route_deviation", "偏航/路线异常"),
                    ("cargo_damage", "货损货差"),
                    ("vehicle_breakdown", "车辆故障"),
                    ("detained", "扣车扣货"),
                    ("customer_complaint", "客户投诉"),
                    ("temperature", "冷链温度异常"),
                    ("fuel", "油耗/漏油异常"),
                    ("overspeed", "超速驾驶"),
                    ("fatigue", "疲劳驾驶"),
                    ("deviation", "偏航（车联网）"),
                    ("abnormal_stop", "异常停车"),
                    ("geofence", "围栏进出"),
                    ("offline", "设备离线"),
                    ("receipt_pending", "回单待确认"),
                    ("other", "其他"),
                ],
                max_length=64,
            ),
        ),
    ]
