# Generated by Django 5.2.15 on 2026-07-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0023_alter_exceptionrecord_exception_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cod_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="代收货款金额（司机代货主向收货人收取）",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cod_status",
            field=models.CharField(
                choices=[
                    ("none", "无代收"),
                    ("pending", "待代收"),
                    ("collected", "已代收"),
                    ("remitted", "已回款"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="freight_payer",
            field=models.CharField(
                choices=[
                    ("shipper", "发货方"),
                    ("consignee", "收货方"),
                    ("third_party", "第三方"),
                ],
                default="shipper",
                help_text="运费承担方",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="freight_term",
            field=models.CharField(
                choices=[
                    ("prepaid", "现付"),
                    ("collect", "到付"),
                    ("receipt", "回单付"),
                    ("monthly", "月结"),
                ],
                default="prepaid",
                help_text="运费付款方式",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="cod_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="waybill",
            name="cod_collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waybill",
            name="cod_remitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waybill",
            name="cod_status",
            field=models.CharField(
                choices=[
                    ("none", "无代收"),
                    ("pending", "待代收"),
                    ("collected", "已代收"),
                    ("remitted", "已回款"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="freight_payer",
            field=models.CharField(
                choices=[
                    ("shipper", "发货方"),
                    ("consignee", "收货方"),
                    ("third_party", "第三方"),
                ],
                default="shipper",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="freight_term",
            field=models.CharField(
                choices=[
                    ("prepaid", "现付"),
                    ("collect", "到付"),
                    ("receipt", "回单付"),
                    ("monthly", "月结"),
                ],
                default="prepaid",
                max_length=16,
            ),
        ),
    ]
