# Generated by Django 5.2.15 on 2026-07-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0024_order_cod_amount_order_cod_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="damaged_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="货损数量", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("full", "整签"),
                    ("partial", "部分签收"),
                    ("rejected", "拒收"),
                ],
                default="full",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="rejection_reason",
            field=models.CharField(
                blank=True, help_text="拒收/异常原因", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="shortage_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="货差（短少）数量", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="signed_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="实收件数/数量", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="total_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="应收件数/数量", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="waybill",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("pending_dispatch", "待调度"),
                    ("dispatched", "已派车"),
                    ("loaded", "已装车"),
                    ("departed", "已发车"),
                    ("in_transit", "运输中"),
                    ("arrived", "已到达"),
                    ("partially_signed", "部分签收"),
                    ("rejected", "已拒收"),
                    ("signed", "已签收"),
                    ("delivered", "已送达"),
                    ("settled", "已结算"),
                    ("cancelled", "已取消"),
                    ("voided", "已作废"),
                ],
                default="pending_dispatch",
                max_length=32,
            ),
        ),
    ]
