# Generated by Django 5.2.16 on 2026-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0025_receipt_damaged_quantity_receipt_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="platform_name",
            field=models.CharField(
                blank=True, help_text="网货平台名称，如 满帮/路歌", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="platform_order_no",
            field=models.CharField(
                blank=True, help_text="平台侧运单/订单号", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="waybill",
            name="dispatch_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("own_vehicle", "自营单车"),
                    ("fleet", "自营车队"),
                    ("third_party", "外包承运商"),
                    ("platform", "网货平台"),
                ],
                max_length=16,
            ),
        ),
    ]
