# Generated by Django 5.2.16 on 2026-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0026_waybill_platform_name_waybill_platform_order_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverreminder",
            name="level",
            field=models.CharField(
                choices=[("normal", "普通"), ("important", "重要"), ("urgent", "紧急")],
                default="important",
                help_text="普通/重要/紧急",
                max_length=16,
            ),
        ),
    ]
