# Generated by Django 5.2.16 on 2026-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0027_driverreminder_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("ftl", "整车"),
                    ("ltl", "零担"),
                    ("express", "快递"),
                    ("coldchain", "冷链"),
                    ("hazmat", "危化"),
                ],
                default="ftl",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("individual", "个体"),
                    ("enterprise", "企业"),
                    ("government", "政府"),
                ],
                default="enterprise",
                max_length=16,
            ),
        ),
    ]
