# Generated by Django 5.2.16 on 2026-07-19 15:25

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0004_loginattempt"),
        ("masterdata", "0012_customer_category_customer_level"),
        ("ops", "0029_order_assigned_at_order_assigned_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_no", models.CharField(max_length=40, unique=True)),
                (
                    "dispatch_type",
                    models.CharField(
                        choices=[
                            ("third_party", "外包承运商"),
                            ("platform", "网货平台"),
                        ],
                        default="third_party",
                        max_length=16,
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        blank=True,
                        help_text="网货平台名称，如 满帮/路歌",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("dispatched", "已派车"),
                            ("partial", "部分完成"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="dispatched",
                        max_length=16,
                    ),
                ),
                (
                    "allocation",
                    models.CharField(
                        choices=[
                            ("by_weight", "按吨占比"),
                            ("even", "均摊"),
                            ("manual", "逐单指定"),
                        ],
                        default="by_weight",
                        max_length=16,
                    ),
                ),
                (
                    "total_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="批次总议定应付",
                        max_digits=14,
                    ),
                ),
                ("order_count", models.IntegerField(default=0)),
                (
                    "total_weight_ton",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_batches",
                        to="masterdata.carrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "派车批次",
                "verbose_name_plural": "派车批次",
                "db_table": "ops_dispatch_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="waybill",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waybills",
                to="ops.dispatchbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchbatch",
            index=models.Index(
                fields=["status", "-created_at"], name="ops_dispatc_status_42cb37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchbatch",
            index=models.Index(
                fields=["carrier", "status"], name="ops_dispatc_carrier_9b056f_idx"
            ),
        ),
    ]
