# Generated by Django 5.2.16 on 2026-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0030_dispatchbatch_waybill_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchbatch",
            name="statement_no",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
