# Generated by Django 5.2.16 on 2026-07-19 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0031_dispatchbatch_statement_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exceptionrecord",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exceptions",
                to="ops.order",
            ),
        ),
        migrations.AddField(
            model_name="exceptionrecord",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
