# Generated by Django 5.2.15 on 2026-06-04 15:25

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('settlement_type', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '承运商',
                'verbose_name_plural': '承运商',
                'db_table': 'md_carrier',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('settlement_type', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'md_customer',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('id_no', models.CharField(blank=True, max_length=32)),
                ('license_no', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='masterdata.carrier')),
            ],
            options={
                'verbose_name': '司机',
                'verbose_name_plural': '司机',
                'db_table': 'md_driver',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plate_no', models.CharField(max_length=32, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('ownership_type', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='masterdata.carrier')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'db_table': 'md_vehicle',
                'ordering': ['plate_no'],
            },
        ),
    ]
