# Generated by Django 5.2.15 on 2026-06-17 14:33

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("origin", models.CharField(blank=True, max_length=80)),
                ("destination", models.CharField(blank=True, max_length=80)),
                (
                    "waypoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="规划路径点 [[lng,lat], ...]",
                    ),
                ),
                (
                    "corridor_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        help_text="允许偏航走廊(米)",
                        max_digits=10,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "线路",
                "verbose_name_plural": "线路",
                "db_table": "md_route",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="license_expiry",
            field=models.DateField(blank=True, help_text="驾照到期日", null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="license_type",
            field=models.CharField(
                blank=True, help_text="准驾车型，如 A2", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="qualification_cert_no",
            field=models.CharField(blank=True, help_text="从业资格证号", max_length=64),
        ),
        migrations.AddField(
            model_name="driver",
            name="qualification_expiry",
            field=models.DateField(blank=True, help_text="从业资格证到期日", null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="inspection_expiry",
            field=models.DateField(blank=True, help_text="年检到期日", null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_expiry",
            field=models.DateField(blank=True, help_text="保险到期日", null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="maintenance_due_date",
            field=models.DateField(blank=True, help_text="下次维保日期", null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="road_transport_cert_no",
            field=models.CharField(blank=True, help_text="道路运输证号", max_length=64),
        ),
    ]
