# Generated by Django 5.2.15 on 2026-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0002_route_driver_license_expiry_driver_license_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="load_capacity_ton",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="核载吨位", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="volume_capacity_cbm",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="容积(方)", max_digits=10
            ),
        ),
    ]
