# Generated by Django 5.2.15 on 2026-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0003_vehicle_load_capacity_ton_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("employee", "自有员工"),
                    ("outsourced", "外协外调"),
                    ("carrier_driver", "承运商司机"),
                    ("temp", "临时"),
                ],
                db_index=True,
                default="employee",
                help_text="雇佣关系：员工/外调/承运商司机/临时，决定结算路径",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_class",
            field=models.CharField(
                choices=[
                    ("tractor", "牵引车"),
                    ("trailer", "挂车"),
                    ("rigid", "单体车"),
                ],
                db_index=True,
                default="rigid",
                help_text="牵引车/挂车/单体车",
                max_length=16,
            ),
        ),
    ]
