# Generated by Django 5.2.15 on 2026-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0004_driver_employment_type_vehicle_vehicle_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="wechat_group",
            field=models.CharField(
                blank=True, help_text="所属微信群聊（需求入口）", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="app_registered",
            field=models.BooleanField(
                db_index=True, default=False, help_text="司机App注册状态"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="app_registered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="cumulative_freight",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="累计运费", max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="cumulative_waybills",
            field=models.IntegerField(default=0, help_text="累计运单数"),
        ),
        migrations.AddField(
            model_name="driver",
            name="wechat",
            field=models.CharField(blank=True, help_text="微信号", max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="dispatch_source",
            field=models.CharField(
                choices=[("own", "自有"), ("external", "外调"), ("platform", "平台")],
                db_index=True,
                default="own",
                help_text="调车来源：自有/外调/平台",
                max_length=16,
            ),
        ),
    ]
