# Generated by Django 5.2.15 on 2026-06-23 09:46

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0005_customer_wechat_group_driver_app_registered_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cred_type",
                    models.CharField(
                        choices=[
                            ("vehicle_license", "车头行驶证"),
                            ("trailer_license", "车挂行驶证"),
                            ("driving_license", "驾驶证"),
                            ("transport_cert", "道路运输证"),
                            ("id_card", "身份证"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("main", "主页/正面"), ("back", "副页/反面")],
                        default="main",
                        max_length=8,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="credentials/"),
                ),
                ("file_url", models.URLField(blank=True)),
                (
                    "ocr_status",
                    models.CharField(
                        default="pending",
                        help_text="pending/processing/done/failed",
                        max_length=16,
                    ),
                ),
                ("ocr_result", models.JSONField(blank=True, default=dict)),
                (
                    "holder_name",
                    models.CharField(
                        blank=True, help_text="识别出的姓名/车牌", max_length=64
                    ),
                ),
                (
                    "cert_no",
                    models.CharField(
                        blank=True, help_text="识别出的证号", max_length=64
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, help_text="有效期至", null=True),
                ),
                (
                    "self_uploaded",
                    models.BooleanField(
                        default=False, help_text="司机自传(True)或代上传(False)"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="masterdata.driver",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "司机证件",
                "verbose_name_plural": "司机证件",
                "db_table": "md_driver_credential",
                "ordering": ["driver", "cred_type", "side"],
                "indexes": [
                    models.Index(
                        fields=["driver", "cred_type"],
                        name="md_driver_c_driver__395968_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="md_driver_c_expiry__62e24e_idx"
                    ),
                ],
            },
        ),
    ]
