# Generated by Django 5.2.15 on 2026-06-29 06:49

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_drivercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BPartner',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('partner_type', models.CharField(choices=[('shipper', '发货方'), ('consignee', '收货方'), ('supplier', '供应商/承运商')], db_index=True, max_length=16)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, help_text='详细物理地址', max_length=255)),
                ('city', models.CharField(blank=True, help_text='归属城市（标准化城市名，如无锡）', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '上下游伙伴',
                'verbose_name_plural': '上下游伙伴',
                'db_table': 'md_b2b_partner',
                'ordering': ['code'],
            },
        ),
    ]
