# Generated by Django 5.2.15 on 2026-07-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0007_b2bpartner"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_day",
            field=models.IntegerField(
                default=1, help_text="账单日（每月几号出账，1-28）"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_days",
            field=models.IntegerField(
                default=30, help_text="账期天数（账单日后 N 天到期）"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="授信额度（0 表示不限）",
                max_digits=14,
            ),
        ),
    ]
