# Generated by Django 5.2.15 on 2026-07-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0008_customer_billing_day_customer_credit_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stake", "高栏"),
                    ("flatbed", "平板"),
                    ("van", "厢式"),
                    ("reefer", "冷藏"),
                    ("hazmat", "危运"),
                    ("fence", "仓栅"),
                    ("wing", "飞翼"),
                    ("tank", "罐式"),
                ],
                help_text="车厢结构：高栏/平板/厢式/冷藏/危运…",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_length_m",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="车长(米)，如 4.2/6.8/9.6/13/17.5",
                max_digits=4,
            ),
        ),
    ]
