# Generated by Django 5.2.16 on 2026-07-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0009_vehicle_body_type_vehicle_vehicle_length_m"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="billing_day",
            field=models.IntegerField(
                default=1, help_text="账单日（每月几号出账，1-28）"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="blacklist_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="carrier",
            name="blacklisted",
            field=models.BooleanField(default=False, help_text="拉黑后不可被派单"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="business_license_no",
            field=models.CharField(blank=True, help_text="营业执照号", max_length=64),
        ),
        migrations.AddField(
            model_name="carrier",
            name="credit_days",
            field=models.IntegerField(
                default=30, help_text="账期天数（账单日后 N 天到期）"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对我方授信额度（0 表示不限）",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "A · 优质"),
                    ("B", "B · 良好"),
                    ("C", "C · 关注"),
                    ("D", "D · 高风险"),
                ],
                default="B",
                help_text="承运商综合评级",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="qualification_expiry",
            field=models.DateField(
                blank=True, help_text="承运资质/经营许可到期日；过期不可派单", null=True
            ),
        ),
    ]
