# Generated by Django 5.2.16 on 2026-07-19 06:33

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0010_carrier_billing_day_carrier_blacklist_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="carrier_type",
            field=models.CharField(
                choices=[
                    ("owner_fleet", "个体车队"),
                    ("company_fleet", "公司车队"),
                    ("platform", "网货平台"),
                    ("temporary", "临时承运商"),
                ],
                db_index=True,
                default="owner_fleet",
                help_text="个体车队/公司车队/网货平台/临时承运商",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="city",
            field=models.CharField(blank=True, help_text="所在城市", max_length=64),
        ),
        migrations.AddField(
            model_name="carrier",
            name="contract_expiry",
            field=models.DateField(blank=True, help_text="合作合同有效期至", null=True),
        ),
        migrations.AddField(
            model_name="carrier",
            name="insurance_expiry",
            field=models.DateField(
                blank=True, help_text="承运人责任险到期日", null=True
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="service_area",
            field=models.CharField(
                blank=True, help_text="服务区域/常跑区域，逗号分隔", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="tax_no",
            field=models.CharField(blank=True, help_text="开票税号", max_length=64),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_license_no",
            field=models.CharField(
                blank=True, help_text="道路运输经营许可证号", max_length=64
            ),
        ),
        migrations.CreateModel(
            name="CarrierLanePrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "origin_city",
                    models.CharField(
                        db_index=True, help_text="起点城市", max_length=64
                    ),
                ),
                (
                    "dest_city",
                    models.CharField(
                        db_index=True, help_text="终点城市", max_length=64
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True, help_text="车型，如 高栏/厢式", max_length=64
                    ),
                ),
                (
                    "vehicle_length_m",
                    models.DecimalField(
                        decimal_places=1, default=0, help_text="车长(米)", max_digits=4
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="标准价", max_digits=12
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="最低价", max_digits=12
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="最高价", max_digits=12
                    ),
                ),
                (
                    "last_deal_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="最近成交价",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(blank=True, help_text="有效期起", null=True),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, help_text="有效期止", null=True),
                ),
                (
                    "is_preferred",
                    models.BooleanField(default=False, help_text="是否常用"),
                ),
                (
                    "is_recommended",
                    models.BooleanField(default=False, help_text="是否推荐"),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lane_prices",
                        to="masterdata.carrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "线路承运商价库",
                "verbose_name_plural": "线路承运商价库",
                "db_table": "md_carrier_lane_price",
                "ordering": ["origin_city", "dest_city", "standard_price"],
                "indexes": [
                    models.Index(
                        fields=["origin_city", "dest_city", "is_active"],
                        name="md_carrier__origin__d49214_idx",
                    )
                ],
            },
        ),
    ]
