# Generated by Django 5.2.16 on 2026-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0011_carrier_carrier_type_carrier_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="category",
            field=models.CharField(
                default="enterprise", help_text="个体/企业/政府", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="level",
            field=models.CharField(
                choices=[
                    ("S", "S · 战略"),
                    ("A", "A · 重点"),
                    ("B", "B · 常规"),
                    ("C", "C · 一般"),
                    ("D", "D · 观察"),
                ],
                db_index=True,
                default="B",
                max_length=1,
            ),
        ),
    ]
