# Generated by Django 5.2.15 on 2026-06-04 15:30

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSuggestion',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已采纳'), ('rejected', '已驳回')], default='pending', max_length=24)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('tool_name', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_suggestions', to='ops.waybill')),
            ],
            options={
                'verbose_name': 'AI 建议',
                'verbose_name_plural': 'AI 建议',
                'db_table': 'ai_agent_suggestion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['suggestion_type', 'status'], name='ai_agent_su_suggest_412a49_idx')],
            },
        ),
    ]
