# Generated by Django 5.2.15 on 2026-06-04 15:16

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'), models.Index(fields=['action', 'created_at'], name='audit_log_action_97df64_idx')],
            },
        ),
    ]
