# Generated by Django 5.2.15 on 2026-06-04 15:25

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('receivable', '应收'), ('payable', '应付'), ('external', '外部费用')], max_length=16)),
                ('debit_account_code', models.CharField(blank=True, max_length=64)),
                ('credit_account_code', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '费用项',
                'verbose_name_plural': '费用项',
                'db_table': 'fin_expense_item',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=16)),
                ('expense_item_code', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('risk_status', models.CharField(default='normal', max_length=32)),
                ('source_system', models.CharField(blank=True, max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': '费用记录',
                'verbose_name_plural': '费用记录',
                'db_table': 'fin_expense_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(max_length=64, unique=True)),
                ('counterparty_type', models.CharField(blank=True, max_length=32)),
                ('counterparty_ref', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='created', max_length=32)),
                ('external_approval_no', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': '付款申请',
                'verbose_name_plural': '付款申请',
                'db_table': 'fin_payment_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
