# Generated by Django 5.2.15 on 2026-06-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ops.waybill'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='waybill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='ops.waybill'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['waybill', 'direction'], name='fin_expense_waybill_fff84d_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['direction', 'risk_status'], name='fin_expense_directi_cc9aef_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status'], name='fin_payment_status_ed7ada_idx'),
        ),
    ]
