# Generated by Django 5.2.15 on 2026-06-04 16:26

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('target_url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=80)),
                ('events', models.CharField(default='*', help_text='逗号分隔事件名；* 表示全部', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhook',
                'db_table': 'fin_webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('price_type', models.CharField(choices=[('income', '收入价'), ('cost', '支出价')], max_length=16)),
                ('expense_item_code', models.CharField(max_length=64)),
                ('route_name', models.CharField(blank=True, max_length=160)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.IntegerField(default=0, help_text='数值大者优先')),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='masterdata.carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='masterdata.customer')),
            ],
            options={
                'verbose_name': '报价规则',
                'verbose_name_plural': '报价规则',
                'db_table': 'fin_pricing_rule',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['price_type', 'is_active'], name='fin_pricing_price_t_337b53_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', help_text='pending/success/failed', max_length=16)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='finance.webhook')),
            ],
            options={
                'verbose_name': 'Webhook 投递',
                'verbose_name_plural': 'Webhook 投递',
                'db_table': 'fin_webhook_delivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='fin_webhook_status_2b2f1b_idx')],
            },
        ),
    ]
