# Generated by Django 5.2.15 on 2026-06-17 15:07

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_webhook_pricingrule_webhookdelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement_no", models.CharField(max_length=40, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("receivable", "应收"), ("payable", "应付")],
                        max_length=16,
                    ),
                ),
                (
                    "counterparty_type",
                    models.CharField(
                        choices=[("customer", "客户"), ("carrier", "承运商")],
                        max_length=16,
                    ),
                ),
                ("counterparty_id", models.CharField(blank=True, max_length=64)),
                ("counterparty_name", models.CharField(blank=True, max_length=160)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("item_count", models.IntegerField(default=0)),
                (
                    "external_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="对方提供金额，用于差异稽核",
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("confirmed", "已确认"),
                            ("settled", "已结算"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "对账单",
                "verbose_name_plural": "对账单",
                "db_table": "fin_statement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("waybill_no", models.CharField(blank=True, max_length=40)),
                ("expense_item_code", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.statement",
                    ),
                ),
            ],
            options={
                "db_table": "fin_statement_line",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(
                fields=["direction", "status"], name="fin_stateme_directi_d5c98d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(
                fields=["counterparty_type", "counterparty_id"],
                name="fin_stateme_counter_7264fc_idx",
            ),
        ),
    ]
