# Generated by Django 5.2.15 on 2026-06-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_statement_statementline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenserecord",
            name="payee_ref",
            field=models.CharField(
                blank=True, help_text="收/付款方名称或标识", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="payee_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="carrier/driver/fuel_card/customer/other",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="remark",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
