# Generated by Django 5.2.15 on 2026-06-23 10:19

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_expenserecord_payee_ref_expenserecord_payee_type_and_more"),
        ("ops", "0020_drivercheckin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reimb_no", models.CharField(max_length=40, unique=True)),
                (
                    "order_no",
                    models.CharField(
                        blank=True,
                        help_text="关联订单号（勾选订单提交时带入）",
                        max_length=40,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("freight_advance", "运费垫付"),
                            ("toll", "过路费"),
                            ("fuel", "油费"),
                            ("loading", "装卸费"),
                            ("lodging", "食宿"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("approved", "已审批"),
                            ("rejected", "已驳回"),
                            ("paid", "已付款"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reimbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reimbursements",
                        to="finance.paymentrequest",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_reimbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reimbursements",
                        to="ops.waybill",
                    ),
                ),
            ],
            options={
                "verbose_name": "报销",
                "verbose_name_plural": "报销",
                "db_table": "fin_reimbursement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="fin_reimbur_status_d70e71_idx"
                    ),
                    models.Index(
                        fields=["waybill", "status"],
                        name="fin_reimbur_waybill_27c9ce_idx",
                    ),
                ],
            },
        ),
    ]
