# Generated by Django 5.2.15 on 2026-06-30 02:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_reimbursement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['-priority', 'name'], 'verbose_name': '多维报价规则', 'verbose_name_plural': '多维报价规则'},
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='price_per_ton',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='fuel_surcharge_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='燃油附加费率，如 2.5% 填 0.025', max_digits=6),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='tier_prices',
            field=models.JSONField(blank=True, default=list, help_text="阶梯报价: [{'min_ton': 0, 'max_ton': 5, 'price': 200}, {'min_ton': 5, 'max_ton': 999, 'price': 180}]"),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='volumetric_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.3333'), help_text='重抛比，如 1方=333kg，填 0.3333', max_digits=8),
        ),
    ]
