# Generated by Django 5.2.15 on 2026-06-30 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_pricingrule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="audited_at",
            field=models.DateTimeField(
                blank=True, help_text="最近一次 AI 异常审计时间", null=True
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="baseline_avg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="deviation_pct",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="expense_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statement_lines",
                to="finance.expenserecord",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="is_anomaly",
            field=models.BooleanField(default=False),
        ),
    ]
