# Generated by Django 5.2.15 on 2026-07-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_statement_audited_at_statementline_baseline_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="charge_method",
            field=models.CharField(
                choices=[
                    ("tiered_weight", "按重量阶梯"),
                    ("flat", "整车一口价"),
                    ("per_volume", "按方计费"),
                    ("per_piece", "按件计费"),
                    ("per_km", "按公里计费"),
                    ("per_ton_km", "吨公里计费"),
                ],
                default="tiered_weight",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pricingrule",
            name="min_charge_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="最低计费量（方/件/吨，不足按此计）",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="pricingrule",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="按方/件/公里/吨公里的单价",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="起步价/固定价", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="最低计费额（金额下限）",
                max_digits=12,
            ),
        ),
    ]
