# Generated by Django 5.2.16 on 2026-07-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0009_pricingrule_charge_method_pricingrule_min_charge_qty_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="expenserecord",
            name="calculation_detail",
            field=models.JSONField(
                blank=True, default=dict, help_text="计算明细（各段金额/附加费）"
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="charge_method",
            field=models.CharField(blank=True, help_text="计费方式快照", max_length=32),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="input_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="计费输入快照（重量/体积/件数/里程）",
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="matched_condition",
            field=models.CharField(
                blank=True,
                help_text="命中的匹配条件（客户/承运商/线路/车型）",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="price_source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="价格来源：recommended(综合推荐)/cheapest(最低价)/lane_price(线路价库)/manual(人工)/platform(平台)/rule(规则)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="pricing_rule_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="pricing_rule_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="quote_id",
            field=models.CharField(
                blank=True, help_text="报价/线路价库条目标识", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="expenserecord",
            name="rule_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="规则字段快照（当时的单价/阶梯/下限等）",
            ),
        ),
    ]
