# Generated by Django 5.2.16 on 2026-07-19 23:29

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_expenserecord_calculation_detail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="约定收/付款到期日，用于账龄与逾期判定", null=True
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="settled_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="累计已收/付款（核销）金额",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="settled_at",
            field=models.DateTimeField(blank=True, help_text="全额结清时间", null=True),
        ),
        migrations.AlterField(
            model_name="statement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("confirmed", "已确认"),
                    ("partial", "部分结算"),
                    ("settled", "已结算"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="StatementPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank", "银行转账"),
                            ("cash", "现金"),
                            ("wechat", "微信"),
                            ("alipay", "支付宝"),
                            ("offset", "冲抵/对冲"),
                            ("acceptance", "承兑汇票"),
                            ("other", "其他"),
                        ],
                        default="bank",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateField(help_text="实际收/付款日期")),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, help_text="银行流水号/凭证号", max_length=80
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.statement",
                    ),
                ),
            ],
            options={
                "verbose_name": "收付款核销",
                "verbose_name_plural": "收付款核销",
                "db_table": "fin_statement_payment",
                "ordering": ["-paid_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["statement"], name="fin_stateme_stateme_9078a3_idx"
                    )
                ],
            },
        ),
    ]
