# Generated by Django 5.2.15 on 2026-06-04 15:51

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key_id', models.CharField(max_length=40, unique=True)),
                ('secret', models.CharField(max_length=80)),
                ('scopes', models.CharField(blank=True, help_text='逗号分隔权限点；* 表示全部', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='iam.organization')),
            ],
            options={
                'verbose_name': 'API 密钥',
                'verbose_name_plural': 'API 密钥',
                'db_table': 'iam_api_key',
                'ordering': ['-created_at'],
            },
        ),
    ]
