# Generated by Django 5.2.15 on 2026-06-30 16:04

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_apikey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["sort_order", "code"],
                "verbose_name": "组织",
                "verbose_name_plural": "组织",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="business_phone",
            field=models.CharField(blank=True, help_text="业务电话", max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="complaint_phone",
            field=models.CharField(blank=True, help_text="投诉电话", max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="district",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="manager_name",
            field=models.CharField(blank=True, help_text="负责人", max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="manager_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_property",
            field=models.CharField(
                choices=[
                    ("self", "自营"),
                    ("franchise", "加盟"),
                    ("outsource", "外包"),
                    ("partner", "合作"),
                    ("jv", "合资"),
                ],
                default="self",
                help_text="经营属性",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="province",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="receipt_return_address",
            field=models.CharField(
                blank=True, help_text="司机回单寄回地址", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="service_phone",
            field=models.CharField(blank=True, help_text="客服电话", max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="short_name",
            field=models.CharField(blank=True, help_text="组织简称", max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("group", "集团"),
                    ("company", "公司"),
                    ("region", "片区"),
                    ("dept", "部门"),
                    ("station", "网点"),
                ],
                default="dept",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="iam.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="iam.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "db_table": "iam_department",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_no",
                    models.CharField(help_text="工号", max_length=32, unique=True),
                ),
                ("name", models.CharField(max_length=64)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("id_no", models.CharField(blank=True, max_length=32)),
                (
                    "position",
                    models.CharField(blank=True, help_text="职位", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "在职"),
                            ("disabled", "停用"),
                            ("left", "离职"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("leave_date", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="iam.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="iam.organization",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="直接上级",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="iam.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "员工",
                "verbose_name_plural": "员工",
                "db_table": "iam_employee",
                "ordering": ["employee_no"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="iam.employee",
            ),
        ),
        migrations.CreateModel(
            name="AccountHandover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("moved_reports", models.IntegerField(default=0)),
                ("moved_departments", models.IntegerField(default=0)),
                ("disabled_account", models.BooleanField(default=False)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handovers_out",
                        to="iam.employee",
                    ),
                ),
                (
                    "to_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handovers_in",
                        to="iam.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号移交",
                "verbose_name_plural": "账号移交",
                "db_table": "iam_account_handover",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="employee_groups", to="iam.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组",
                "verbose_name_plural": "用户组",
                "db_table": "iam_employee_group",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="iam.employeegroup"
            ),
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("deliver", "派送区域"),
                            ("transfer", "中转区域"),
                            ("special", "特殊区域"),
                            ("no_deliver", "不派送区域"),
                            ("no_transfer", "不中转区域"),
                        ],
                        default="deliver",
                        max_length=16,
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=32)),
                ("city", models.CharField(blank=True, max_length=32)),
                ("district", models.CharField(blank=True, max_length=32)),
                (
                    "region_code",
                    models.CharField(
                        blank=True, help_text="行政区划编码", max_length=16
                    ),
                ),
                (
                    "region_name",
                    models.CharField(help_text="区划展示名", max_length=120),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="多网点覆盖时的优先级，越大越优先"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务区划",
                "verbose_name_plural": "服务区划",
                "db_table": "iam_service_area",
                "ordering": ["-priority", "region_name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "status"], name="iam_employe_organiz_2dbc79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["status"], name="iam_employe_status_a79826_idx"),
        ),
        migrations.AddIndex(
            model_name="servicearea",
            index=models.Index(
                fields=["organization", "area_type"],
                name="iam_service_organiz_04089b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicearea",
            index=models.Index(
                fields=["region_code"], name="iam_service_region__90b267_idx"
            ),
        ),
    ]
