# Generated by Django 5.2.15 on 2026-07-09 04:13

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_alter_organization_options_organization_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("success", models.BooleanField(default=False)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("bad_credentials", "凭据错误"),
                            ("inactive", "账号停用"),
                            ("locked", "已锁定"),
                        ],
                        default="bad_credentials",
                        max_length=32,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "登录审计",
                "verbose_name_plural": "登录审计",
                "db_table": "iam_login_attempt",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["username", "created_at"],
                        name="iam_login_a_usernam_6419ca_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="iam_login_a_success_35208f_idx",
                    ),
                ],
            },
        ),
    ]
