# Generated by Django 5.2.9 on 2026-06-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='api.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=32, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='api.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_no', models.CharField(max_length=40, unique=True)),
                ('route_name', models.CharField(max_length=160)),
                ('origin', models.CharField(blank=True, max_length=80)),
                ('destination', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='pending_dispatch', max_length=32)),
                ('dispatch_status', models.CharField(default='pending_accept', max_length=32)),
                ('risk_level', models.CharField(default='none', max_length=16)),
                ('receipt_status', models.CharField(default='not_due', max_length=32)),
                ('eta_drift_minutes', models.IntegerField(default=0)),
                ('cargo_quantity', models.IntegerField(default=0)),
                ('cargo_weight_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cargo_volume_cbm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='api.carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='api.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='api.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='api.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reported_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='api.waybill')),
            ],
            options={
                'ordering': ['reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=16)),
                ('expense_item_code', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_status', models.CharField(default='normal', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.waybill')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='pending_handle', max_length=32)),
                ('responsibility_party', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='api.waybill')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(default='pending', max_length=24)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_suggestions', to='api.waybill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('event_time', models.DateTimeField()),
                ('resource', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.waybill')),
            ],
            options={
                'ordering': ['event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['status', 'risk_level'], name='api_waybill_status_5fadc2_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['receipt_status'], name='api_waybill_receipt_5d7c50_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingpoint',
            index=models.Index(fields=['reported_at'], name='api_trackin_reporte_e61105_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['direction', 'risk_status'], name='api_expense_directi_3d3bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['exception_type', 'status'], name='api_excepti_excepti_fe2110_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsuggestion',
            index=models.Index(fields=['suggestion_type', 'status'], name='api_agentsu_suggest_38198c_idx'),
        ),
        migrations.AddIndex(
            model_name='waybillevent',
            index=models.Index(fields=['event_type', 'event_time'], name='api_waybill_event_t_477c9e_idx'),
        ),
    ]
