# Generated by Django 5.2.15 on 2026-06-17 14:13

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
        ("ops", "0002_receipt_exceptionrecord_assignee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_no", models.CharField(max_length=64, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("gps", "GPS 定位"),
                            ("beidou", "北斗定位"),
                            ("temperature", "温度传感器"),
                            ("fuel", "油耗传感器"),
                            ("etc", "ETC"),
                            ("adas", "ADAS 前向安全"),
                            ("dsm", "DSM 驾驶行为"),
                        ],
                        default="gps",
                        max_length=16,
                    ),
                ),
                ("sim_no", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "在线"), ("offline", "离线")],
                        default="offline",
                        max_length=16,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="masterdata.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "车载终端",
                "verbose_name_plural": "车载终端",
                "db_table": "tel_device",
                "ordering": ["device_no"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("overspeed", "超速"),
                            ("fatigue", "疲劳驾驶"),
                            ("deviation", "偏航"),
                            ("abnormal_stop", "异常停车"),
                            ("geofence", "围栏进出"),
                            ("temperature", "温度异常"),
                            ("fuel", "油量异常"),
                            ("offline", "设备离线"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "提示"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("acknowledged", "已确认"),
                            ("closed", "已关闭"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField()),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="masterdata.vehicle",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="ops.waybill",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="telematics.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "报警",
                "verbose_name_plural": "报警",
                "db_table": "tel_alert",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lng",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "lat",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "speed_kmh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("heading", models.IntegerField(default=0, help_text="方向角 0-359")),
                (
                    "mileage_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fuel_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("online", models.BooleanField(db_index=True, default=False)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_state",
                        to="masterdata.vehicle",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_states",
                        to="ops.waybill",
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆实时状态",
                "verbose_name_plural": "车辆实时状态",
                "db_table": "tel_vehicle_state",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type", "status"], name="tel_device_device__57ec41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type", "status"], name="tel_alert_alert_t_cefcb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["vehicle", "status"], name="tel_alert_vehicle_5ffdf1_idx"
            ),
        ),
    ]
