# Generated by Django 5.2.15 on 2026-06-17 14:28

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0001_initial"),
        ("telematics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "shape",
                    models.CharField(
                        choices=[("circle", "圆形"), ("polygon", "多边形")],
                        default="circle",
                        max_length=16,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("warehouse", "仓库/卸货点"),
                            ("route", "线路区域"),
                            ("restricted", "限行区域"),
                        ],
                        default="warehouse",
                        max_length=16,
                    ),
                ),
                (
                    "center_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "center_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "radius_m",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "polygon",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="多边形顶点 [[lng,lat], ...]",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "电子围栏",
                "verbose_name_plural": "电子围栏",
                "db_table": "tel_geofence",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inside", models.BooleanField(default=False)),
                ("since", models.DateTimeField(blank=True, null=True)),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_states",
                        to="telematics.geofence",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_states",
                        to="masterdata.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "围栏进出状态",
                "verbose_name_plural": "围栏进出状态",
                "db_table": "tel_geofence_state",
                "unique_together": {("vehicle", "geofence")},
            },
        ),
    ]
